### PR TITLE
chore(playground): update playground file names and imports to match best practices

### PR DESCRIPTION
**Pull request by brandyscarney**
Updates the Angular, React and Vue files to follow our best practices guide:

> *Angular:* Prefer the following format: `[name of component]_component_[type of file].md`
> 
> Example: `example_component.html.md`
> 
> *React:* Prefer the following format: `main_[type of file].md`
> 
> Example: `main_css.md`
> 
> *Vue*: Prefer the following format `[name of component]_vue.md`
> 
> Example: `modal_vue.md`

### CODE REVIEW

**Comment by sean-perkins** [comment]
This may completely bust the JP build. Let's hold on merging until we can vet that. Otherwise we need to open an identical PR against that branch with the same file renames.

**Review by sean-perkins — APPROVED** [review]
I did more exploration in this and I think we are safe here! 

The main problem we run into with the JP build, is renaming the folder structure of where the Playground component is imported from in the docs page. Since we are changing the lower level files, I _think_ it'll be fine.

**Review by liamdebeasi — APPROVED** [review]

**Review by amandaejohnston — APPROVED** [review]

**Comment by brandyscarney** [comment]
@sean-perkins Should I merge it and see if it breaks all of the things? 😬

**Comment by sean-perkins** [comment]
@brandyscarney go for it! I can fix the JP build again over JEDI day if I was wrong 😆

**Pull request merged**
