### PR TITLE
feat(jp): update translation/jp to v7

### PR DESCRIPTION
**Pull request by rdlabo**
This can be merged until Ionic 7 GA is available.

### CODE REVIEW

**Comment by rdlabo** [comment]
スクリーンショット 2023-03-21 午後3 05 48

In v7, Japanese documentation will automatically translated using DeepL for properties and other parts that can be handled by scripts.
https://github.com/ionic-team/ionic-docs/pull/2837/commits/51dc415a74ce32cd2cc7d704e6b07c2ef6888cd8

**Comment by rdlabo** [comment]
Memo: We will proofread the translation of DeepL, like this commit: https://github.com/ionic-team/ionic-docs/pull/2837/commits/079ca83a117fb08ec47d0c65c0ccae96b51de226

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
Hey there,

Thanks for all of the hard work translating the Ionic v7 documentation. We really appreciate it! As I understand it, this documentation was translated using DeepL with most of it reviewed by either you or another developer in the Ionic community.

According to https://github.com/ionic-team/ionic-docs/pull/2837#issuecomment-1477329364, not all of the translated content has been reviewed. Could we update this PR to only include the content that has been reviewed and approved by a person?

We'd like to start by merging only the reviewed content. As other content gets reviewed we are happy to accept those contributions in separate PRs. Please let me know if you have any questions.

**Comment by rdlabo** [comment]
@liamdebeasi Now, all content has been reviewed and approved by me👍

https://github.com/ionic-team/ionic-docs/pull/2837/commits/a8df44b4c9c42b126b865ecf09edcddedc8cca68

**Comment by rdlabo** [comment]
Memo: Conflicting is resolved by merge main branch: https://github.com/ionic-team/ionic-docs/pull/2837/commits/b47bf2a3566d1cbb1741348926a3124b05950949

This pull request can be merge now(need force push)

**Review by liamdebeasi — APPROVED** [review]
Thank you!

**Pull request merged**
