### PR TITLE
Improve Coverage of Options for Config

### PR DESCRIPTION
**Pull request by pecknigel**
Add information on modifying config at a platform level, working with the config from within components.

### CODE REVIEW

**Comment by brandyscarney** [comment]
Thank you for the PR! Could you fix the merge conflicts from merging this PR please: https://github.com/ionic-team/ionic-docs/pull/532

**Comment by nigelbpeck** [comment]
That's done, Brandy, I also did some restructuring and pulling more information in. It should have everything there is to know about it now. If you only want the original changes that were merged, you can take 9b142b9. Let me know any problems, hopefully I got all the Git stuff right, but I'm new to submitting a PR.

**Comment by nigelbpeck** [comment]
@brandyscarney Was this no good Brandy? Really happy to make changes, rewrite it, whatever is needed to get it up to scratch. I added a lot of stuff here to try and include everything that can be done with the config, based on documentation I read, and checking on things with Mike in the Slack channel.

**Comment by brandyscarney** [comment]
@nigelbpeck I've added Mike to give an initial review. 🙂 Thank you!

**Comment by nigelbpeck** [comment]
Great, thanks 🙏 will look our for updates 👍

**Comment by liamdebeasi** [comment]
Thanks for the PR, and apologies for the delay. We've made a few changes to Ionic that should address the concerns here. In particular:

1. We've added documentation on the different config methods in Ionic Angular: https://ionicframework.com/docs/developing/config#reading-the-config-angular
2. The tabs placement config on `ion-tabs` has been removed in favor of the `placement` property on `ion-tab-bar` with the release of Ionic v4.0: https://github.com/ionic-team/ionic-framework/blob/c1eabb7333bf6e807de5bce166b287834fb60f32/BREAKING_ARCHIVE/v4.md?plain=1#L1566
3. The `platforms` config option no longer exists. Instead, we expose utility functions for setting the config based on the mode: https://ionicframework.com/docs/developing/config#per-platform-config

I am going to close this PR, but let me know if you have questions.

**Pull request closed without merging**
