### PR TITLE
update(native): Update native.json

### PR DESCRIPTION
**Pull request by stephanejais**

### CODE REVIEW

**Comment by dotNetkow** [comment]
hi, thanks for the PR. The section of the Ionic Native docs has gotten very out of sync (docs vs ionic native repo) - the team has some work to do to fix it.  In the meantime, is there anything specific you need added/updated? I can apply it.

**Comment by stephanejais** [comment]
@dotNetkow Absolutely! Thank you for asking. I was looking forward to get the WonderPush plugin description updated. Lines 3913-3915 of native.json. Thanks a lot.

**Comment by stephanejais** [comment]
> hi, thanks for the PR. The section of the Ionic Native docs has gotten very out of sync (docs vs ionic native repo) - the team has some work to do to fix it. In the meantime, is there anything specific you need added/updated? I can apply it.

Thanks @dotNetkow, here's a patch.

[patch.txt](https://github.com/ionic-team/ionic-docs/files/4169712/patch.txt)

**Comment by dotNetkow** [comment]
Great, thanks! I just applied the updates - they should go live shortly.

**Comment by stephanejais** [comment]
> Great, thanks! I just applied the updates - they should go live shortly.

Thank you very much for these changes. We were hoping to change the displayName to "Push Notifications - WonderPush" as well, could you make that change also?

Kind regards.

**Comment by dotNetkow** [comment]
sure - sorry I missed that part. [done!](https://github.com/ionic-team/ionic-docs/commit/36875f38d3748a9d39f61c17ffd7f7fbd9bafb39)

**Comment by stephanejais** [comment]
Thanks!

**Pull request closed without merging**
