### PR TITLE
docs(slides): remove ion-slides component

### PR DESCRIPTION
**Pull request by amandaejohnston**
In v7, we are removing `ion-slides`, `ion-slide`, and `IonicSwiper`. In accordance with this, this PR:

- Removes the component docs
- Removes links to the components from the sidebar
- Updates the framework-specific migration docs with callouts

Corresponding framework PR: https://github.com/ionic-team/ionic-docs/pull/2507

### CODE REVIEW

**Comment by liamdebeasi** [comment]
What do you think we should do about the "Slides" card on https://ionicframework.com/docs/components?

**Comment by sean-perkins** [comment]
Can we remove this section from the FAQ for each framework:

> If you are running into problems with the IonicSlides module, new bugs should be filed on the Ionic Framework repo: https://github.com/ionic-team/ionic-framework/issues

**Comment by amandaejohnston** [comment]
> What do you think we should do about the "Slides" card on https://ionicframework.com/docs/components?
> 
> Maybe we should keep the `ion-slides` page and reference the framework-specific pages in the content? I do worry that the Swiper.js recommendation will be a bit buried.

Hmm, I'm thinking we just remove the card entirely, since we're handing things off fully to a 3rd party library 🤔 The recommendation will be linked in the breaking changes guide, which may be enough? What do you think?

We can always revisit if we start getting questions/feature requests about slides/carousels. I'm hesitant to keep the component pages because it feels like unnecessary clutter.

**Comment by amandaejohnston** [comment]
> Can we remove this section from the FAQ for each framework:
> 
> > If you are running into problems with the IonicSlides module, new bugs should be filed on the Ionic Framework repo: https://github.com/ionic-team/ionic-framework/issues

You may be getting `IonicSlides` and `IonicSwiper` confused? We're keeping `IonicSlides`.

**Comment by amandaejohnston** [comment]
@liamdebeasi @sean-perkins Not sure how notifications work in this situation 😆

**Comment by liamdebeasi** [comment]
> Hmm, I'm thinking we just remove the card entirely, since we're handing things off fully to a 3rd party library 🤔 The recommendation will be linked in the breaking changes guide, which may be enough? What do you think?

> We can always revisit if we start getting questions/feature requests about slides/carousels. I'm hesitant to keep the component pages because it feels like unnecessary clutter.

That's probably fine. We do have "Slides" pages for each framework integration.

**Comment by liamdebeasi** [comment]
You could also ask Ben and see what he thinks too

**Review by liamdebeasi — APPROVED** [review]
Just need to remove the "Slides" option from https://ionic-docs-git-fw-1363-ionic1.vercel.app/docs/components and we will be good to go.

**Review by sean-perkins — APPROVED** [review]

**Pull request merged**
