### PR TITLE
docs(range): pins playground

### PR DESCRIPTION
**Pull request by sean-perkins**
Introduces the component playground for displaying a pin with `ion-range`. 

Quick link: https://ionic-docs-git-range-playground-pins-ionic1.vercel.app/docs/api/range#pins

### CODE REVIEW

**Comment by sean-perkins** [comment]
Need to add an example with `pinFormatter`, adding that soon!

**Review by amandaejohnston — APPROVED** [review]

**Review by liamdebeasi — CHANGES_REQUESTED** [review]
The code snippets are missing `<IonContent>` so the range will appear in the middle of the screen instead of at the top.

**Comment by liamdebeasi** [comment]
Good to merge once that is addressed though

**Comment by sean-perkins** [comment]
Good catch, I'll update all open PRs with that change as well 👍

**Pull request merged**
