### PR TITLE
docs(many): unversion guide, cli, and native

### PR DESCRIPTION
**Pull request by liamdebeasi**
This PR updates the docs such that the "Guide", "Native", and "CLI" sections of the Ionic Docs are no longer subject to versioning.

## What Changed?

- The "Guide" section has been moved to an unversioned `guide` directory
- The "Native" section has been moved to an unversioned `native` directory
- The "CLI" section has been moved to an unversioned `cli` directory
- Updated numerous links to account for the `/docs/guide` change (see below)
- Updated numerous links that are broken even in `main`

⚠️ As part of this change, contents in the "Guide" section now exist under the URL `/docs/guide`. This is because we cannot have separate sections of our docs use the same `routeBasePath` due to https://github.com/facebook/docusaurus/issues/5651. Prior to merging this PR we should create 301 redirects for old versioned content as well as this link change.

## Why are we making this change?

There are a few problems with the current infrastructure:

1. **The versioning for Native and Docs is inaccurate**
The versioning of the docs is tied to the Ionic Framework version, not the version of any native or CLI packages. As a result, if you went to `https://ionicframework.com/docs/v6/cli` you would get information about Ionic CLI v7 on the Ionic Framework v6 docs site, not information about Ionic CLI v6.

2. **Pages are hard to maintain**
Any time we need to make a change to a page we need to make that same change two more times. This increases the workload for making any kind of content change on the docs. This is especially true for changes to pages in the "Guides" section that are applicable to multiple versions. It also makes it harder for community to contribute because they may not be aware of these versioned pages. With the exception of the API docs, many of these pages do not change frequently meaning versioning is not valuable for them.

3. **Increases build time**
Having so many additional files make the docs site slow to build and deploy.

4. **Translations are hard to maintain**
In particular, the Japanese docs need to be translated 3x similar to issue 2. However, whenever we version the docs we effectively lose translations for the previous version.

## Miscellaneous

**Is the version dropdown moving?**

After consulting with Ben we decided **not to move the version dropdown**. We wanted to prioritize a consistent UI as we felt the dropdown selectively appearing on pages was confusing. This behavior aligns with how Docusaurus websites with versioned and unversioned content behave.

Jest: https://jestjs.io/ (Click the "Help" page and change the version)
Docusaurus: https://docusaurus.io/docs (Click the "Showcase" page and change the version)

**What will the version dropdown control?**

The version dropdown will only control content in the `docs` directory. This means it will only control the docs for the UI components and the associated API (i.e. everything in https://ionicframework.com/docs/components and `https://ionicframework.com/docs/api/*`)

**Do we need 301 redirects?**

Yes, we need them for the following:
<details>

<summary>Click to expand (long list)</summary>

- `docs/` --> `docs/guide/intro`
- `docs/intro/*` --> `docs/guide/intro/*`
- `docs/developing/*` --> `docs/guide/developing/*`
- `docs/layout/*` --> `docs/guide/layout/*`
- `docs/theming/*` --> `docs/guide/theming/*`
- `docs/angular/*` --> `docs/guide/angular/*`
- `docs/react/*` --> `docs/guide/react/*`
- `docs/vue/*` --> `docs/guide/vue/*`
- `docs/utilities/*` --> `docs/guide/utilities/*`
- `docs/deployment/*` --> `docs/guide/deployment/*`
- `docs/techniques/*` --> `docs/guide/technique/*`
- `docs/troubleshooting/*` --> `docs/guide/troubleshooting/*`
- `docs/core-concepts/*` --> `docs/guide/core-concepts/*`
- `docs/contributing/*` --> `docs/guide/contributing/*`
- `docs/reference/*` --> `docs/guide/reference/*`

- `docs/v6/cli/*` --> `docs/cli/*`
- `docs/v6/native/*` --> `docs/native/*`
- `docs/v6/` --> `docs/guide/intro`
- `docs/v6/intro/*` --> `docs/guide/intro/*`
- `docs/v6/developing/*` --> `docs/guide/developing/*`
- `docs/v6/layout/*` --> `docs/guide/layout/*`
- `docs/v6/theming/*` --> `docs/guide/theming/*`
- `docs/v6/angular/*` --> `docs/guide/angular/*`
- `docs/v6/react/*` --> `docs/guide/react/*`
- `docs/v6/vue/*` --> `docs/guide/vue/*`
- `docs/v6/utilities/*` --> `docs/guide/utilities/*`
- `docs/v6/deployment/*` --> `docs/guide/deployment/*`
- `docs/v6/techniques/*` --> `docs/guide/technique/*`
- `docs/v6/troubleshooting/*` --> `docs/guide/troubleshooting/*`
- `docs/v6/core-concepts/*` --> `docs/guide/core-concepts/*`
- `docs/v6/contributing/*` --> `docs/guide/contributing/*`
- `docs/v6/reference/*` --> `docs/guide/reference/*`

- `docs/v5/cli/*` --> `docs/cli/*`
- `docs/v5/native/*` --> `docs/native/*`
- `docs/v5/` --> `docs/guide/intro`
- `docs/v5/intro/*` --> `docs/guide/intro/*`
- `docs/v5/developing/*` --> `docs/guide/developing/*`
- `docs/v5/layout/*` --> `docs/guide/layout/*`
- `docs/v5/theming/*` --> `docs/guide/theming/*`
- `docs/v5/angular/*` --> `docs/guide/angular/*`
- `docs/v5/react/*` --> `docs/guide/react/*`
- `docs/v5/vue/*` --> `docs/guide/vue/*`
- `docs/v5/utilities/*` --> `docs/guide/utilities/*`
- `docs/v5/deployment/*` --> `docs/guide/deployment/*`
- `docs/v5/techniques/*` --> `docs/guide/technique/*`
- `docs/v5/troubleshooting/*` --> `docs/guide/troubleshooting/*`
- `docs/v5/core-concepts/*` --> `docs/guide/core-concepts/*`
- `docs/v5/contributing/*` --> `docs/guide/contributing/*`
- `docs/v5/reference/*` --> `docs/guide/reference/*`
</details>

### CODE REVIEW

**Comment by brandyscarney** [comment]
I reviewed the redirects and there are some directories missing. The following are missing on purpose but could we add why we aren't adding redirects to these by the section on redirects: 

`/docs/cli` (URL did not change)
`/docs/native` (URL did not change)
`/docs/updating` (did not exist on v6)

-----

For the `/docs/developer-resources` directory I think we might need to add a redirect for this or get rid of its mention:

It is mentioned on [`docs/angular/your-first-app`](https://ionicframework.com/docs/angular/your-first-app) if you click on "See here" in the first info block it takes you to [`guides/first-app-v4/intro`](https://ionicframework.com/docs/developer-resources/guides/first-app-v4/intro) BUT if you try to go to that link by itself it redirects to [`ionic.io/resources`](https://ionic.io/resources). However, you can navigate directly to the v6 version [`docs/v6/developer-resources/guides/first-app-v4/intro`](https://ionicframework.com/docs/v6/developer-resources/guides/first-app-v4/intro) and see the page. 

The v5 version [`docs/v5/developer-resources/guides/first-app-v4/intro`](https://ionicframework.com/docs/v5/developer-resources/guides/first-app-v4/intro) also redirects to [`ionic.io/resources`](https://ionic.io/resources).

-----

Is the `api` file versioned properly? If I go to the [v5 api index](https://ionicframework.com/docs/v5/api) I can navigate to breadcrumb but it says page not found. I see this on the main site though too so maybe we just need to create a separate ticket to fix this but I wanted to bring it up.

**Comment by liamdebeasi** [comment]
For the API index, it looks like that specific page is not versioned correctly. Breadcrumbs was added in v6, but the index looks to be pulling in from the latest version (note that slides and virtual scroll are not present.

**Comment by brandyscarney** [comment]
I went through clicking around the documentation and found broken links. I didn't verify they were all due to this change so some may be unrelated. 

Broken links in the Guide documentation:

- The `Ionic CLI` link here is broken: hhttps://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide#ionic-cli
- The `ionic generate` and `the documentation` links here are broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/developing/scaffolding#generating-new-features
- The `Ionic CLI` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/developing/tips#using-the-ios-simulator
- All links on this page are broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/layout/structure
- Both links in this section are broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/theming/css-variables#component-variables-1
- The `select documentation` link is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/theming/css-shadow-parts#exposing-a-part
- The `Component documentation` and `component documentation page` links are broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/theming/css-shadow-parts#ionic-framework-parts
- The `Learn more here` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/troubleshooting/debugging#live-reload
- The `Ionic Native` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/core-concepts/cross-platform#ionic-native
- The `Grid` links (both) here are broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/core-concepts/cross-platform#layout
- The `@awesome-cordova-plugins/ionic-webview` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/core-concepts/webview
- The `Ionic's CLI` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/reference/glossary#cli
- The `policy and commitment to stability` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/reference/release-notes
- The `Capacitor installation guide for Cordova plugins` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/reference/support#ionic-platform--products
- The `vanilla JavaScript implementation` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/guide/reference/support#ionic-platform--products-cont


Broken links in the grid API documentation:

- The `CSS Utilities` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/api/grid#overview
- The `Variables in Media Queries` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/api/grid#default-breakpoints
- The `css utilities` links here are broken in both places: 
  - https://ionic-docs-git-unversion-ionic1.vercel.app/docs/api/grid#vertical-alignment
  - https://ionic-docs-git-unversion-ionic1.vercel.app/docs/api/grid#horizontal-alignment


Broken links in the CLI documentation:

- The `CLI` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/cli
- The `monorepo` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/cli/configuration#multi-app-projects
- The `Web View` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/cli/livereload


Broken links in the Native documentation:

- The `Camera plugin` link here is broken: https://ionic-docs-git-unversion-ionic1.vercel.app/docs/native/setup#usage

----

I did not go through the Angular, React or Vue guide sections, all of the API components, the CLI command reference or the Native Plugins section. Any links to `guide`, `cli` or `native` documentation will need to be updated in those places too.

**Comment by liamdebeasi** [comment]
This has been put on hold until we can make more progress on translation infrastructure.

**Pull request closed without merging**
