### PR TITLE
docs(popover): add nested playground

### PR DESCRIPTION
**Pull request by amandaejohnston**
Adds the Nested Popovers playground. `dismissOnSelect` was folded in here rather than having its own separate playground, since separating the two felt redundant.

### CODE REVIEW

**Review by liamdebeasi — COMMENTED** [review]
Clicking "More options..." does not dismiss the popover on the JavaScript and Angular StackBlitz demos but does dismiss the popover on the Vue and React demos

**Comment by amandaejohnston** [comment]
Looks to be an Ionic bug 🤔 I'll investigate a little and get an issue posted.

**Comment by amandaejohnston** [comment]
Done: https://github.com/ionic-team/ionic-framework/issues/25324

**Review by sean-perkins — APPROVED** [review]
Outside of the reported bug, everything else looks good to me 👍

**Review by liamdebeasi — APPROVED** [review]

**Pull request merged**
