### PR TITLE
translation(jp): 20230824 updated

### PR DESCRIPTION
**Pull request by rdlabo**

### CODE REVIEW

**Comment by liamdebeasi** [comment]
Hey there! Can you fill out the PR description so I can understand what this does?

**Comment by rdlabo** [comment]
This is simply the latest version of the document merged and translated.

However, since we use the main branch of https://github.com/ionic-jp/ionic-docs as our working branch, we always end up with a lot of diffs when we do pull requests.

**Comment by liamdebeasi** [comment]
Thanks! Did you mean to merge this into the `translation/jp` branch instead of `main`? This PR currently overwrites the English documentation.

**Comment by rdlabo** [comment]
@liamdebeasi 
 https://github.com/ionic-jp/ionic-docs  <- Japanese repository
 https://github.com/ionic-team/ionic-docs <- This repository

I said "we worked on  https://github.com/ionic-jp/ionic-docs"

**Comment by rdlabo** [comment]
Sorry, it was an operational error. Terminate this pull request to make the target branch correct. Thanks for letting me know!

**Pull request closed without merging**
